{% set version = '1.3.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cgdsr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cgdsr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cgdsr/cgdsr_{{ version }}.tar.gz
  sha256: 4aa2a3564cee2449c3ff39ab2ad631deb165d4c78b8107e0ff77a9095340cc1f

build:
  number: 5
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r.methodss3
    - r-r.oo
    - r-httr
  run:
    - r-base
    - r-r.methodss3
    - r-r.oo
    - r-httr

test:
  commands:
    - $R -e "library('cgdsr')"           # [not win]
    - "\"%R%\" -e \"library('cgdsr')\""  # [win]

about:
  home: https://github.com/cBioPortal/cgdsr
  license: LGPL-3.0-only
  summary: Provides a basic set of R functions for querying the Cancer Genomics Data Server (CGDS),
    hosted by the Computational Biology Center at Memorial-Sloan-Kettering Cancer Center
    (MSKCC) at <www.cbioportal.org>.
  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: cgdsr
# Type: Package
# Title: R-Based API for Accessing the MSKCC Cancer Genomics Data Server (CGDS)
# Version: 1.3.0
# Date: 2019-06-10
# Author: Anders Jacobsen <jacobsen@cbio.mskcc.org>, Augustin Luna <lunaa@cbio.mskcc.org>
# Maintainer: Benjamin Gross <cgdsr@cbioportal.org>
# Description: Provides a basic set of R functions for querying the Cancer Genomics Data Server (CGDS), hosted by the Computational Biology Center at Memorial-Sloan-Kettering Cancer Center (MSKCC) at <www.cbioportal.org>.
# License: LGPL-3
# LazyLoad: yes
# URL: https://github.com/cBioPortal/cgdsr
# Depends: R (>= 3.1)
# Imports: R.oo, R.methodsS3, httr
# Suggests: testthat
# NeedsCompilation: no
# Repository: CRAN
# RoxygenNote: 6.0.1
# Packaged: 2019-06-25 20:01:11 UTC; wilson
# Date/Publication: 2019-06-26 11:50:22 UTC
