travis:
  secure:
    BINSTAR_TOKEN: c52pddDGdCnGP9Fjsm7LgQ5nFPopjup5gMrT87VwJrGecGOakaauJmAE5RRg5GYAc0WvlP/QQHsETJnDbnw5Oqj9cARSkuWE90PMNTVm6Znq4sZOPd/aTLx1H/Dn0JkpENQq8M8nmXGyQSe9g+/FVeo+rejSgm1X6l6mUNsBeDvFxh0jTVqxXX5KqPQU4xmj6ZX79E/SmdGxWgWMZjesqVzNe3v0XzSs8AgJM2Wf49JYipdHIfwu5WKtWLCrGgFvp5nIdZUKtZ8zsy6iuU6eUyNNrP8ntZjkt8ZWd8FEJKGQ9qPtWVVHTkfUQjt2BdmtUxP5yce3aDFFSptwJzsLwBytTXZmM00ZfRMTynPSdl/C0UX+HJK1yRmKJ20J40xtvvy/JfIXl0NprL9vWJNWjf/Qpqqk7WvNB49HRwrZ8mTPVRypEV5BMZWoesQlUcmu0z/1onJP8ew0ZSum0Fq9gDq78FrKtjwBo4WoaomDR6kDv7mcvWgM2ctMDdgnprmJsgliUHHOQnhatc/WTmGI0m6V66jOsB8EBS7eE1Z/eAaijPD100LZvSR9n5IjUr6R2mUrg5HhcU/F+4Yc7uLDNif9Qhi5LZZAoCS0vsiYhMoEKgaAl8HbCRX5d1/nyKW2Hyt9zVY75axzuD3sb84wTdqmIKz54iQ8Rk8jpITOh5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
