appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jSoqOWeoRNcBuPAJerkwwTQ0Js9/eJzTgfhiUZKHzIsoJ2LdK0pqqfxFxBUwzO/oiidWBFTLTP5XoO8aNNSMdunQPkpBQfaSYvsvuccwraqmduRESH7X9cCF23skXQBgWBGpGsIGn0kejWMexAknVq7vE0JOJ5id2VpWbDYKt7s1OJgnPWwWbTbaQD4OvAic3MyUpMt4UpeloOtYn9Ii8wjgvdsi3Z4ZQu2bTBFIfvinOVTfHBdvrkSH+0ilv9XctGdfQlp1SFUUV3OZ7yMsnzXfJl0rM0RC5z5+qNIgbui/076wiuVRFNsiDnXhZOwi/Ym5IiW0bRaT7hPqf+5X9VRTdIauk7bRi1TZhc51u7GR5XmH3cuodT76exy+cKohx+2Jd8Tdjg/lI+Gft33vby/zFEuEuuNx3fTfv9CC3FQ+L9qan/jR82s2pzdSj2pqpQctB5gy7DoVUEluFZphb9lHOlgIb7t3npth4yNFNB8+ryWx+O0ysQj7ZVIwHxWEs/jyCWcXYZ3A9h/GJGctNg19APTQooRP0oIk3Lkzol6fan1OVtJZlO9+sPlVHQzd9C3C+Yq4khg9QtuqtvOtR2+2SSEVQccjJREvcjNFFlsYoPDXTVCwEOevJABlpvwJn/7O1VgXA3LsdlBOJZSbEgqOCItYJhI2CMpHPpegsxw=}
