travis:
  secure:
    BINSTAR_TOKEN: nUb7X25/TrU2u+8lbHNuiVPPK4ra1klL8l9WA0e2tnu2nCD1eAZ9aiuDcZvQzha5YUTEbmKowJI6c+CIZYzkRFoGbT1jakDu14Kk+4rJQm8Cwl+Oh2pcvYEcNw4EoT/4o8XkmwDSgnX37EYKKeG7T5cBjAbTkslce6IfWuRSSY+TjcrcsSkUK2rKaR3rifujtlB5dLTHPCGc0YYVCf4+f2SybHPJ0Op1dM5ccBuH4+jr06KoRtOOkOVeiws/yPNd+1W7DDTwf8cn7HEWWdiKGNIiTUNplBBrWnAdsJkGcVyge/QBcR1IkkJUYKkjxYkM7fhFvDsoP7nhfDkexqKG5qsq+ywJFpMV4wxpBVckcmG6zEjRXvA1M7hygOTwIypRyYjlsDmRAJI79ITqwKJndhnGLRwaxsawUSZ5+Ve3cUQQuGbLYRglWJ7mc56L81BjwstWqAYOy00WhReEgH+htUYc697b7Wf+nwl9TKcVCLnMnuVy45rRIxbDGAAbSrfvy6eHDdHbQe2TucgaQyxbwf8gGxLbuWzgyO/adpCzFWLNJ3NoSYF0yJZz3SSQj5rOWWr9ReFuLQQY8iXjlTWnWkue3wDff8cow9dMfs/voyu5T0+wtOgup8wplrIKjgJuXPiP40uaJ0PzGtr+cREclWow88jUQJlhi3y/S5WNlWk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
